version: "4.3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  backend_service:
    build: ./backend
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo_db:27017/
      FRONTEND_URL  : http://localhost:5173
    depends_on:
      - mongo_db
  frontend_service:
    build: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - mongo_db
      - backend_service

volumes:
  mongo_db: {}